---
title: "IP_MS_ANALYSIS"
author: "Finn"
date: ", Last edited on `r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

### MYD88

``` {r, warning = FALSE, message = FALSE, echo = FALSE}
library(tidyverse)
library(data.table)
library(janitor)
library(ggrepel)
library(knitr)
library(svglite)
library(readxl)
library(UniprotR)
library(plotly)

################################################################################
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE, fig.height=7, fig.width=14)
options(stringsAsFactors = FALSE)
theme_set(theme_bw())
theme_update(panel.grid.minor = element_blank())

################################################################################

### DEFINE PATHS
MAIN    = ifelse(dir.exists("/Volumes/TAYLOR-LAB/Finn/RESULTS/IP_MS_2/"), 
                 yes =  "/Volumes/TAYLOR-LAB/Finn/RESULTS/IP_MS_2/",
                 no  =  "~/Documents/Github/transferGit/")
FILES_LOC  = "~/Documents/Github/master_thesis/"
ANNOTATE = T

```


``` {r}
FOLDER = "MYD88"
OUT    = paste0(FILES_LOC, FOLDER)
```

``` {r}
if (ANNOTATE == T) {
  if (file.exists(paste0(FILES_LOC, "ANNOTATED/", FOLDER,"_fromJSON_ANNOTATED.csv"))) {
    MAIN <- read.csv(paste0(FILES_LOC, "ANNOTATED/", FOLDER,"_fromJSON_ANNOTATED.csv"))
  } else if (file.exists(paste0(FILES_LOC, "ANNOTATED/", FOLDER,"_ANNOTATED.csv"))) {
    MAIN <- read.csv(paste0(FILES_LOC, "ANNOTATED/", FOLDER,"_ANNOTATED.csv"))
  } else print("Please make sure correct path was provided or change to ANNOTATE = F.")
} else {
  MAIN <- fread(paste0(FILES_LOC, "JSON_PROCESSED/", FOLDER,"_fromJSON.csv"))
  if (file.exists(paste0(FILES_LOC, "JSON_PROCESSED/", FOLDER,"_fromJSON.csv"))) {
    MAIN <- read.csv(paste0(FILES_LOC, "JSON_PROCESSED/", FOLDER,"_fromJSON.csv"))
    MAIN$RECYCLE_num <-unlist(lapply(strsplit(MAIN$RECYCLE, "_", fixed=TRUE), function(x) return(x[2])))
  } else if (file.exists(paste0(FILES_LOC, "SLURM_PROCESSED/", FOLDER,".csv"))) {
    MAIN <- read.csv(paste0(FILES_LOC, "SLURM_PROCESSED/", FOLDER,".csv"))
  } else print("Please make sure correct path was provided or change to ANNOTATE = F.")
}

## HISTOGRAM
  MAIN %>% #group_by(FILE) %>% filter(iScore == max(iScore)) %>% 
    ggplot(aes(iScore, fill = as.factor(N_MONOMERS))) +
    geom_vline(xintercept = 0.4, col = "gray40", linetype = "dotted", linewidth = 1) +
    geom_vline(xintercept = 0.5, col = "cornflowerblue", linetype = "dotted", linewidth = 1) +
    geom_vline(xintercept = 0.7, col = "lightgreen", linetype = "dotted", linewidth = 1) +
    geom_histogram(bins = 30) +
    expand_limits(x=c(0,1)) +
    annotate("text", x = 0.4, y = -0.05, label = "medium \n confidence") +
    annotate("text", x = 0.5, y = -0.05, label = "high \n confidence") +
    annotate("text", x = 0.7, y = -0.05, label = "very high \n confidence") +
    ggtitle("Model Confidence assessed by iScore")
```

``` {r}
## iScore vs. piTM plot
  SIGNIF_PROTEINS <- MAIN %>% filter(iScore >= 0.4, !is.na(Gene.Names)) %>% distinct(FILE, .keep_all = T)
  MAIN <- MAIN %>% mutate(SIGNIF = case_when(MAIN$FILE %in% SIGNIF_PROTEINS$FILE  ~ T,
                                             !MAIN$FILE %in% SIGNIF_PROTEINS$FILE ~ F),
                          Entry.Name = case_when(!is.na(Entry.Name) ~ Entry.Name,
                                                 is.na(Entry.Name) ~ FILE))
  max_SIGNIF_PROTEINS <- SIGNIF_PROTEINS %>% group_by(FILE) %>% summarise(iScore = max(iScore))
  
  MAIN_PLOT <- MAIN %>% ggplot(aes(iScore, piTM, 
                      col = as.factor(N_MONOMERS),
                      label = Entry.Name)) +
    geom_abline(col = "gray") +
    geom_point(size = 3) +
    ggrepel::geom_label_repel(data = MAIN, show.legend = F) +
    scale_x_continuous(name = "iScore", breaks = c(0, 0.4, 0.5, 0.7, 1)) +
    scale_y_continuous(name = "piTM", breaks = c(0, 0.5, 1)) +
    theme(legend.position = "bottom") +
    scale_color_discrete(name = "Complex Size") +
    ggtitle(paste0('Computational screening for PPI partners of ', FOLDER)) +
    expand_limits(x=c(0,1), y=c(0,1)) +
    annotate("text", x = 0.4, y = -0.05, label = "medium \n confidence") +
    annotate("text", x = 0.5, y = -0.05, label = "high \n confidence") +
    annotate("text", x = 0.7, y = -0.05, label = "very high \n confidence")
  
  #MAIN_PLOT
  ggplotly(MAIN_PLOT)
```



### IRAK4

``` {r}
FOLDER = "IRAK4"
OUT    = paste0(FILES_LOC, FOLDER)
```

``` {r}
if (ANNOTATE == T) {
  if (file.exists(paste0(FILES_LOC, "ANNOTATED/", FOLDER,"_fromJSON_ANNOTATED.csv"))) {
    MAIN <- read.csv(paste0(FILES_LOC, "ANNOTATED/", FOLDER,"_fromJSON_ANNOTATED.csv"))
  } else if (file.exists(paste0(FILES_LOC, "ANNOTATED/", FOLDER,"_ANNOTATED.csv"))) {
    MAIN <- read.csv(paste0(FILES_LOC, "ANNOTATED/", FOLDER,"_ANNOTATED.csv"))
  } else print("Please make sure correct path was provided or change to ANNOTATE = F.")
} else {
  MAIN <- fread(paste0(FILES_LOC, "JSON_PROCESSED/", FOLDER,"_fromJSON.csv"))
  if (file.exists(paste0(FILES_LOC, "JSON_PROCESSED/", FOLDER,"_fromJSON.csv"))) {
    MAIN <- read.csv(paste0(FILES_LOC, "JSON_PROCESSED/", FOLDER,"_fromJSON.csv"))
    MAIN$RECYCLE_num <-unlist(lapply(strsplit(MAIN$RECYCLE, "_", fixed=TRUE), function(x) return(x[2])))
  } else if (file.exists(paste0(FILES_LOC, "SLURM_PROCESSED/", FOLDER,".csv"))) {
    MAIN <- read.csv(paste0(FILES_LOC, "SLURM_PROCESSED/", FOLDER,".csv"))
  } else print("Please make sure correct path was provided or change to ANNOTATE = F.")
}

## HISTOGRAM
  MAIN %>% #group_by(FILE) %>% filter(iScore == max(iScore)) %>% 
    ggplot(aes(iScore, fill = as.factor(N_MONOMERS))) +
    geom_vline(xintercept = 0.4, col = "gray40", linetype = "dotted", linewidth = 1) +
    geom_vline(xintercept = 0.5, col = "cornflowerblue", linetype = "dotted", linewidth = 1) +
    geom_vline(xintercept = 0.7, col = "lightgreen", linetype = "dotted", linewidth = 1) +
    geom_histogram(bins = 30) +
    expand_limits(x=c(0,1)) +
    annotate("text", x = 0.4, y = -0.05, label = "medium \n confidence") +
    annotate("text", x = 0.5, y = -0.05, label = "high \n confidence") +
    annotate("text", x = 0.7, y = -0.05, label = "very high \n confidence") +
    ggtitle("Model Confidence assessed by iScore")
```

``` {r}
## iScore vs. piTM plot
  SIGNIF_PROTEINS <- MAIN %>% filter(iScore >= 0.4, !is.na(Gene.Names)) %>% distinct(FILE, .keep_all = T)
  MAIN <- MAIN %>% mutate(SIGNIF = case_when(MAIN$FILE %in% SIGNIF_PROTEINS$FILE  ~ T,
                                             !MAIN$FILE %in% SIGNIF_PROTEINS$FILE ~ F),
                          Entry.Name = case_when(!is.na(Entry.Name) ~ Entry.Name,
                                                 is.na(Entry.Name) ~ FILE))
  max_SIGNIF_PROTEINS <- SIGNIF_PROTEINS %>% group_by(FILE) %>% summarise(iScore = max(iScore))
  
  MAIN_PLOT <- MAIN %>% ggplot(aes(iScore, piTM, 
                      col = as.factor(N_MONOMERS),
                      label = Entry.Name)) +
    geom_abline(col = "gray") +
    geom_point(size = 3) +
    ggrepel::geom_label_repel(data = MAIN, show.legend = F) +
    scale_x_continuous(name = "iScore", breaks = c(0, 0.4, 0.5, 0.7, 1)) +
    scale_y_continuous(name = "piTM", breaks = c(0, 0.5, 1)) +
    theme(legend.position = "bottom") +
    scale_color_discrete(name = "Complex Size") +
    ggtitle(paste0('Computational screening for PPI partners of ', FOLDER)) +
    expand_limits(x=c(0,1), y=c(0,1)) +
    annotate("text", x = 0.4, y = -0.05, label = "medium \n confidence") +
    annotate("text", x = 0.5, y = -0.05, label = "high \n confidence") +
    annotate("text", x = 0.7, y = -0.05, label = "very high \n confidence")
  
  #MAIN_PLOT
  ggplotly(MAIN_PLOT)
```

### IRAK1

``` {r}
FOLDER = "IRAK1"
OUT    = paste0(FILES_LOC, FOLDER)
```

``` {r}
if (ANNOTATE == T) {
  if (file.exists(paste0(FILES_LOC, "ANNOTATED/", FOLDER,"_fromJSON_ANNOTATED.csv"))) {
    MAIN <- read.csv(paste0(FILES_LOC, "ANNOTATED/", FOLDER,"_fromJSON_ANNOTATED.csv"))
  } else if (file.exists(paste0(FILES_LOC, "ANNOTATED/", FOLDER,"_ANNOTATED.csv"))) {
    MAIN <- read.csv(paste0(FILES_LOC, "ANNOTATED/", FOLDER,"_ANNOTATED.csv"))
  } else print("Please make sure correct path was provided or change to ANNOTATE = F.")
} else {
  MAIN <- fread(paste0(FILES_LOC, "JSON_PROCESSED/", FOLDER,"_fromJSON.csv"))
  if (file.exists(paste0(FILES_LOC, "JSON_PROCESSED/", FOLDER,"_fromJSON.csv"))) {
    MAIN <- read.csv(paste0(FILES_LOC, "JSON_PROCESSED/", FOLDER,"_fromJSON.csv"))
    MAIN$RECYCLE_num <-unlist(lapply(strsplit(MAIN$RECYCLE, "_", fixed=TRUE), function(x) return(x[2])))
  } else if (file.exists(paste0(FILES_LOC, "SLURM_PROCESSED/", FOLDER,".csv"))) {
    MAIN <- read.csv(paste0(FILES_LOC, "SLURM_PROCESSED/", FOLDER,".csv"))
  } else print("Please make sure correct path was provided or change to ANNOTATE = F.")
}

## HISTOGRAM
  MAIN %>% #group_by(FILE) %>% filter(iScore == max(iScore)) %>% 
    ggplot(aes(iScore, fill = as.factor(N_MONOMERS))) +
    geom_vline(xintercept = 0.4, col = "gray40", linetype = "dotted", linewidth = 1) +
    geom_vline(xintercept = 0.5, col = "cornflowerblue", linetype = "dotted", linewidth = 1) +
    geom_vline(xintercept = 0.7, col = "lightgreen", linetype = "dotted", linewidth = 1) +
    geom_histogram(bins = 30) +
    expand_limits(x=c(0,1)) +
    annotate("text", x = 0.4, y = -0.05, label = "medium \n confidence") +
    annotate("text", x = 0.5, y = -0.05, label = "high \n confidence") +
    annotate("text", x = 0.7, y = -0.05, label = "very high \n confidence") +
    ggtitle("Model Confidence assessed by iScore")
```

``` {r}
## iScore vs. piTM plot
  SIGNIF_PROTEINS <- MAIN %>% filter(iScore >= 0.4, !is.na(Gene.Names)) %>% distinct(FILE, .keep_all = T)
  MAIN <- MAIN %>% mutate(SIGNIF = case_when(MAIN$FILE %in% SIGNIF_PROTEINS$FILE  ~ T,
                                             !MAIN$FILE %in% SIGNIF_PROTEINS$FILE ~ F),
                          Entry.Name = case_when(!is.na(Entry.Name) ~ Entry.Name,
                                                 is.na(Entry.Name) ~ FILE))
  max_SIGNIF_PROTEINS <- SIGNIF_PROTEINS %>% group_by(FILE) %>% summarise(iScore = max(iScore))
  
  MAIN_PLOT <- MAIN %>% ggplot(aes(iScore, piTM, 
                      col = as.factor(N_MONOMERS),
                      label = Entry.Name)) +
    geom_abline(col = "gray") +
    geom_point(size = 3) +
    ggrepel::geom_label_repel(data = MAIN, show.legend = F) +
    scale_x_continuous(name = "iScore", breaks = c(0, 0.4, 0.5, 0.7, 1)) +
    scale_y_continuous(name = "piTM", breaks = c(0, 0.5, 1)) +
    theme(legend.position = "bottom") +
    scale_color_discrete(name = "Complex Size") +
    ggtitle(paste0('Computational screening for PPI partners of ', FOLDER)) +
    expand_limits(x=c(0,1), y=c(0,1)) +
    annotate("text", x = 0.4, y = -0.05, label = "medium \n confidence") +
    annotate("text", x = 0.5, y = -0.05, label = "high \n confidence") +
    annotate("text", x = 0.7, y = -0.05, label = "very high \n confidence")
  
  #MAIN_PLOT
  ggplotly(MAIN_PLOT)
```

